#! /bin/sh

# bspc monitor DP-0 -d "" "" "" "" ""
bspc monitor LVDS-1 -d "browse" "code" "read" "chat" "etc"

bspc config border_width 2
bspc config normal_border_color $(get_color color1)
bspc config active_border_color $(get_color color1)
bspc config focused_border_color $(get_color color4)
bspc config window_gap 8

# bspc config top_padding 30
# bspc config -m LVDS-1 top_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true


# App rules
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Code desktop='^2'
bspc rule -a TelegramDesktop desktop='^4' state=pseudo_tiled split_ratio=0.1 center=on
bspc rule -a discord desktop='^4'
bspc rule -a mpv desktop='^5'
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a keepassx state=floating
bspc rule -a transmission-gtk state=psuedo_tiled
bspc rule -a Zathura desktop='^3' state=tiled

