#! /bin/sh

# bspc monitor DP-0 -d "" "" "" "" ""
bspc monitor DP-0 -d "browse" "code" "chat" "music" "etc"

bspc config border_width 2
bspc config normal_border_color $(get_color color1)
bspc config active_border_color $(get_color color1)
bspc config focused_border_color $(get_color color4)
bspc config window_gap 8

bspc config top_padding 30
bspc config -m DVI-D-0 top_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true


# App rules
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Code desktop='^2'
bspc rule -a TelegramDesktop desktop='^6' state=pseudo_tiled split_ratio=0.1 center=on
bspc rule -a discord desktop='^3'
bspc rule -a mpv desktop='^4'
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a keepassx state=floating
bspc rule -a Transmission-gtk state=psuedo_tiled

