# Remove mouse when typing
unclutter &

# Merge xresources for colors etc.
xrdb -merge -I$HOME ~/.Xresources

# Remap caps lock to control
xmodmap ~/.xmodmap

# Turn off anonying beep
xset -b

# Set background
feh --bg-fill ~/Dropbox/pics/wollz/pinkflowers.jpg

# bar
polybar battery &
polybar date &
polybar docked-bar &

# service for  telegram urgency as it doesn't do that itself
telegram-urgency &

# Shortcut manager
sxhkd &

# Window manager
exec bspwm

