# Remove mouse when typing
xbanish &

# Merge xresources for colors etc.
xrdb -merge -I$HOME ~/.Xresources

# Remap caps lock to control
xmodmap ~/.xmodmap

# Turn off anonying beep
xset -b

# Set background
feh --bg-fill ~/Dropbox/pics/wollz/bluepink.png

# bar
polybar bar -r &

# service for  telegram urgency as it doesn't do that itself
telegram-urgency &

# Shortcut manager
sxhkd &

# Window manager
exec bspwm

