#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias lsa='ls -lahF'
alias pls='sudo $(fc -ln -1)'  # Repeat the last command as sudo
alias msc='ncmpcpp -h 192.168.1.12'
alias :q='exit'

shuf -n 1 .minimalism 2> /dev/null | cat

